name: Deploy Production Firebase Hosting
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Allow running this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  npm_compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Flutter Build (Web only)
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.8.0'
          channel: stable
          cache: true
          cache-key: flutter-build-artifacts # optional, change this to force refresh cache
          cache-path: ${{ runner.tool_cache }}/flutter # optional, change this to specify the cache path
      - run: flutter pub get
      - run: flutter build web
      - name: Firebase hosting deploy
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PORTFOLIO_RAJAN_PHADNIS }}'
          projectId: portfolio-rajan-phadnis
          channelId: live
    