name: Deploy Dev Firebase Hosting
'on':
  push:
  # Allow running this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: taiki-e/install-action@v2
        with:
          tool: zola@0.19.2,toml-cli
      - run: toml get config.toml base_url
      - run: zola build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PORTFOLIO_RAJAN_PHADNIS }}'
          channelId: live
          projectId: portfolio-rajan-phadnis
          target: dev