name: Deploy Production Firebase Hosting
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: taiki-e/install-action@v2
        with:
          tool: zola@0.19.2
      - run: zola build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PORTFOLIO_RAJAN_PHADNIS }}'
          channelId: live
          projectId: portfolio-rajan-phadnis
          target: live